brasil = ('Fortaleza', 'Athletico-PR', 'Atlético-GO', 'Bahia', 'Red Bull Bragantino', 'Fluminense', 'Palmeiras', 'Flamengo', 'Atlético-MG','Corinthians','Ceará','Santos','Cuiabá','Sport','São Paulo','Juventude','Internacional','Grêmio','América-MG','Chapecoense')
print(brasil[:5])
print(brasil[-4:])
a = sorted(brasil)
print(sorted(brasil))
print(f"O Chapecoense está na posição {brasil.index('Chapecoense')+1}")
